#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_NFC_MT6605)   += mt6605.o
ccflags-$(CONFIG_NFC_MT6605) +=  -DDEBUG
# //>2015/09/08-Jack, Proting NFC PN544
obj-$(CONFIG_PN544_NFC)    += pn544.o  
# //>2015/09/08-Jack